# Generated by Django 5.0.8 on 2026-06-18 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('held', 'Held'), ('triggered', 'Triggered'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('landlord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrows_as_landlord', to=settings.AUTH_USER_MODEL)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrows_as_tenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EscrowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('triggered', 'Triggered'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, max_length=20)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.escrow')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['status', 'created_at'], name='core_escrow_status_883739_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['tenant_id', 'status'], name='core_escrow_tenant__c50f89_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['landlord_id', 'status'], name='core_escrow_landlor_e214bd_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowevent',
            index=models.Index(fields=['escrow', 'created_at'], name='core_escrow_escrow__31aa58_idx'),
        ),
    ]
